### ISSUE TITLE
Am Error occur while communicating with Data source 

### ISSUE THREAD

**Issue by Munir2020** [RobDWaller/fableau#10]
Hi,
I got an error when trying to connect to Facebook on Tableau
Here is a screenshot
http://prntscr.com/kco416

**Comment by RobDWaller** [comment]
Thanks for highlighting this I've been on holiday but I'll aim to fix this as soon as possible.

**Comment by RobDWaller** [comment]
These issues should be fixed now.

I've had to make significant changes to things including removing some of the Facebook metrics, but it should work fine now.

Let me know if there are any other issues.
